// <auto-generated />
using System;
using AnimalShelterApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimaShelterApi.Migrations
{
    [DbContext(typeof(AnimalShelterApiContext))]
    [Migration("20230609220901_RemoveUserEntity")]
    partial class RemoveUserEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelterApi.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Available")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Breed")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateAdmitted")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Available = true,
                            Breed = "Scruffy",
                            DateAdmitted = new DateTime(2018, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Scratchy",
                            Type = "Cat"
                        },
                        new
                        {
                            AnimalId = 2,
                            Available = true,
                            Breed = "Beagle/Sneaky",
                            DateAdmitted = new DateTime(2022, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cranko",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalId = 3,
                            Available = false,
                            Breed = "Feathered",
                            DateAdmitted = new DateTime(2020, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sporty",
                            Type = "Bird"
                        },
                        new
                        {
                            AnimalId = 4,
                            Available = true,
                            Breed = "Foxhound",
                            DateAdmitted = new DateTime(2022, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Stanley",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalId = 5,
                            Available = true,
                            Breed = "Tabby/Stinky",
                            DateAdmitted = new DateTime(2022, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Borgus",
                            Type = "Cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
